### ISSUE TITLE
Document the format

### ISSUE THREAD

**Issue by Dragas** [zofrex/runeterra_cards#1]
Reading your snippets I see that it's a base32 encoded string, but the logic behind decoding the end result is intertwined with ruby specific extensions. Provide a high level explanation of how the format stores card_id and count combos.

**Comment by zofrex** [comment]
Hi Dragas,

Thank you for opening an issue!

I'm afraid I'm not sure I understand what you're asking for.

If you want an explanation of the format, it's described in the [Readme for this repo](https://github.com/RiotGames/LoRDeckCodes) – is that what you are looking for?

To be clear that repo (LoRDeckCodes) is not my repo, and the format is not mine, they are made by Riot Games. This repo (runeterra_cards) is my implementation of their format.

If what you want is to handle this format in another programming language than Ruby, take a look at the repo I linked above – it has links to implementations in many other languages.

Does that help?

**Comment by zofrex** [comment]
@Dragas I have added a line to the Description section of the README explaining where the specification can be found for the deck code format and the metadata format. Please let me know if that isn't clear!
